### ISSUE TITLE
Reconstruction of datapoints that are not on gplate polygons

### ISSUE THREAD

**Issue by mcranium** [adamkocsis/chronosphere#3]
I tried to calculate the palaeocoordinates of the Burmese Amber field site (26.500250, 96.583361) via the `reconstruct()` command and I got NAs as a return, because the coordinates are not on gplate polygons.
Is there a way to circumvent these kind of issues?

Best wishes,
Mario

**Comment by adamkocsis** [comment]
That is unrelated to chronosphere, and a problem of the plate tectonic model. You should use a different one, then, e.g. 
reconstruct(matrix(c(96.583361, 26.50025),ncol=2), age=100, model="SETON2012")
