### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by zsh-zsh-zsh** [adamkocsis/chronosphere#4]
Hi

when I use the reconstruct() function to reconstrust the map. It showed that:

Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'http://gws.gplates.org/reconstruct/static_polygons/?time=300&model=PALEOMAP': HTTP status was '500 Internal Server Error'

While the coast can be reconstrusted well. And I tried the url and it seems 'http://gws.gplates.org/reconstruct/static_polygons/?time=300&model=PALEOMAP' this won't work with '&model=PALEOMAP'.

Do you know why? Thank you!

**Comment by adamkocsis** [comment]
Hi,

Yes, as the message says, this is an internal server error of the GPlates Web Service. We will let them know that there is an issue.

Until they fix this this, I recommend installing the GPlates desktop application and use the offline reconstruction method instead. If Gplates is installed correctly, you can run reconstruct() the exact same way as before, only you have to specify a downloaded model. For instance the 'paleomap' model is available with fetch(). To reconstruct the plates/static polygons with this, try:

library(chronosphere)
mod <- fetch("paleomap", "model")
reconstruct("plates", age=300, model=mod)

In case GPlates is installed in an other directory than the default, you have to specify the path manually with the 'path.gplates' argument. 

Cheers,

Adam
