### ISSUE TITLE
Reverse dependency check failure with raster 3.6.0

### ISSUE THREAD

**Issue by rsbivand** [adamkocsis/chronosphere#9]
Careful checking of your package as **raster** replaces **rgdal** and **rgeos** is advised. With raster development version 3.6.0 (and PROJ 9.1.0, GDAL 3.5.2), I get:
[00check.log](https://github.com/chronosphere-portal/r_package/files/9487824/00check.log)

**Comment by rsbivand** [comment]
This package and **icosa** depend on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by adamkocsis** [comment]
Thanks for the note! Yes, I am aware of the issue - this package is getting restructured (i.e. broken up), which takes a bit more time than anticipated. I will try to finish this ASAP.

**Comment by rsbivand** [comment]
These are recent check log from running under `_SP_EVOLUTION_STATUS_=2` without retiring r-spatial packages (suggested in these packages) on the library path:
[00check.log](https://github.com/chronosphere-portal/r_package/files/11139030/00check.log)
[00check.log](https://github.com/chronosphere-portal/r_package/files/11139033/00check.log)
Both involve the unconditional use of retiring suggested packages - could you condition on the availability of them as a first correction step, and move to replace use with other packages if the xamples/vignettes are needed?

**Comment by adamkocsis** [comment]
I see, thanks!  The issue should already be resolved for [**icosa**](https://cran.r-project.org/package=icosa). The dependent classes and methods in **chronosphere** were already adapted to work with **sf** and **terra** and were migrated to the alpha version of [**via**](https://cran.r-project.org/package=via).  Now I am refactoring   **chronosphere** and its remote(s) to work with the new dependency. 

I can do a temporary update of **chronosphere**, but that would mean some disruption in the functionality, which I would rather avoid - unless the issue is really-really pressing. If not, the new version should be on CRAN before May.

**Comment by rsbivand** [comment]
By May will be fine, thanks for your cooperation!

**Comment by rsbivand** [comment]
Expect package to fail CRAN CMD check with `_R_CHECK_SUGGESTS_ONLY_=true` when `sp` 2.0-0 is published very soon, if `sf` is not added to Suggests:; currently fails if `sf` not explicitly suggested at:
```
> edge <- mapedge()
Warning in CRS("+proj=longlat") : sf required for evolution_status==2L
> molledge <- spTransform(edge, CRS("+proj=moll"))
Warning in CRS("+proj=moll") : sf required for evolution_status==2L
Error in spTransform(edge, CRS("+proj=moll")) : 
  sf required for evolution_status==2L
Calls: spTransform -> spTransform
```

**Comment by adamkocsis** [comment]
Thanks for the repeated reminder! I was forced to prioritize other projects and this had to be pushed back further.

The new version of [chronosphere](https://cran.r-project.org/package=chronosphere) was submitted to the CRAN yesterday, and with that all references to the old spatial dependencies are resolved - and this issue should be finally resolved for good. I will close the thread.

**Comment by rsbivand** [comment]
Confirmed that 0.5.0 passes CMD check without retiring packages on the library path! Thanks!
